name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Optional) Free up space on the runner
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /usr/share/dotnet || true
          docker system prune -af || true
          df -h

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            docs/requirements.txt
            pyproject.toml

      - name: Install docs dependencies only
        run: |
          python -m pip install -U pip wheel setuptools
          # Prefer a tiny docs requirements file (recommended)
          pip install -r docs/requirements.txt
          pip install -e . --no-deps
          # OR if you have a docs extra:
          # pip install .[docs] -c docs/constraints.txt

      - name: Build Sphinx
        run: |
          sphinx-build -b html docs/ _build/html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
